import { StyleSheet, Platform } from "react-native";
import colors from "./colors";

export default StyleSheet.create({
  container: {
    paddingVertical: 12,
    backgroundColor: colors.background,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.textDark,
    marginLeft: 16,
    marginBottom: 12,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
    letterSpacing: 0.2,
  },
  featuredDeal: {
    backgroundColor: colors.primaryLight,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },
  featuredDealContent: {
    flex: 1,
    marginRight: 12,
  },
  dealText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textDark,
    lineHeight: 24,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  dealSubText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.error,
    marginTop: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  dealCTAContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  dealCTA: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.surface,
    marginRight: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  hotPicksList: {
    paddingHorizontal: 16,
  },
  hotPickCard: {
    width: 300,
    marginRight: 16,
    borderRadius: 16,
    backgroundColor: colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  hotPickImage: {
    width: 90,
    height: 90,
    borderRadius: 12,
  },
  hotPickInfo: {
    flex: 1,
    paddingLeft: 12,
    justifyContent: "center",
  },
  storeNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1, // Allow wrapping if needed
  },
  hotPickName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textDark,
    lineHeight: 20,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  hotPickStore: {
    fontSize: 13,
    color: colors.textLight,
    marginTop: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  timerText: {
    fontSize: 11,
    fontWeight: "500",
    color: colors.error,
    marginTop: 6,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  saveButton: {
    position: "absolute",
    top: 8,
    right: 8,
    padding: 4,
  },
  recommendedList: {
    paddingHorizontal: 16,
  },
  recommendedCard: {
    width: 300,
    marginRight: 16,
    borderRadius: 16,
    backgroundColor: colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  recommendedImage: {
    width: 90,
    height: 90,
    borderRadius: 12,
  },
  recommendedInfo: {
    flex: 1,
    paddingLeft: 12,
    justifyContent: "center",
  },
  recommendedName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textDark,
    lineHeight: 20,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  recommendedCategory: {
    fontSize: 13,
    color: colors.textLight,
    marginTop: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  ratingText: {
    fontSize: 13,
    color: colors.textDark,
    marginLeft: 4,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
  verifiedIcon: {
    marginLeft: 4, // Space between name and checkmark
    color: colors.badge,
  },
  noItemsText: {
    fontSize: 16,
    color: colors.textLight,
    textAlign: "center",
    padding: 10,
    fontFamily: Platform.OS === "ios" ? "System" : "Roboto",
  },
});